// Style reminder: PayLock is the flagship object in the Signal / State system. Use large editorial type, stable graphitic surfaces, lime only for proof and active states, and explicit technical boundaries.
import { useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, Check, CheckCircle2, Cpu, Database, ExternalLink, Layers3, Menu, ShieldCheck, X } from "lucide-react";
import ReferenceMark from "@/components/ReferenceMark";
import PayLockMark from "@/components/PayLockMark";

const stages = [
  { number: "01", name: "Bound request", code: "H0 / INTENT_FROZEN", copy: "Core binds the submitted request payload with a system-issued serial to create H0: the scoped request for the protocol path." },
  { number: "02", name: "Provider readiness", code: "PROVIDER_ACK", copy: "A provider-specific integration translates an authenticated readiness event into the canonical provider_ack meaning. The provider retains its own operating policies." },
  { number: "03", name: "User unlock", code: "USER_UNLOCK", copy: "The documented minimum path records a user_unlock after the defined access step. The exact client and delivery control belongs to the integration contract." },
  { number: "04", name: "H1 proof", code: "H1 / PROOF_ISSUED", copy: "With the current named provider_ack and user_unlock gates present, Core can issue the deterministic H1 proof record." },
];

const modules = [
  { icon: <Cpu size={19} />, number: "01", title: "Core protocol", copy: "The reviewed Core path freezes the request into H0 and guards H1 issuance behind the currently named proof signals." },
  { icon: <Layers3 size={19} />, number: "02", title: "Dictionary + Adapter", copy: "The Dictionary defines a shared event meaning; a provider-specific Adapter must authenticate and translate the provider event before Core receives its canonical signal." },
  { icon: <Database size={19} />, number: "03", title: "Provider environment", copy: "The provider keeps its commercial, compatibility, availability, authentication, and delivery decisions inside its own service environment." },
];

const evidenceLinks = [
  { title: "PayLock Core repository", href: "https://github.com/uniqueteamyemen/paylock-core", label: "github.com/uniqueteamyemen/paylock-core" },
  { title: "Docker Hub repository", href: "https://hub.docker.com/repository/docker/uniqueteamyemen/paylock-core", label: "hub.docker.com/repository/docker/uniqueteamyemen/paylock-core" },
  { title: "YPharma Platform (منصة الدواء)", href: "https://ypharma1.deterministicsolutionsdesign.com/", label: "ypharma1.deterministicsolutionsdesign.com" },
  { title: "Traveler Platform (منصة ترافلر)", href: "https://traveler.deterministicsolutionsdesign.com/", label: "traveler.deterministicsolutionsdesign.com" },
  { title: "System diagnostics", href: "https://qpm5p92k.checkly-status-page.com", label: "Open diagnostics status" },
  { title: "Protocol run video", href: "https://youtu.be/LjBu6G-ASE8", label: "Watch the system run" },
];

export const implementationStatus = [
  { label: "Reviewed Core path", title: "Bound request", state: "IMPLEMENTED", copy: "The reviewed Core path binds the submitted request and a system-issued serial into H0. This statement is limited to the reviewed Core implementation." },
  { label: "Reviewed Core guard", title: "Current H1 condition", state: "IMPLEMENTED", copy: "The reviewed Core issues H1 only after the current named `provider_ack` and `user_unlock` signals are present. H1 is technical delivery evidence only." },
  { label: "Reviewed Core controls", title: "Replay handling", state: "IMPLEMENTED", copy: "The reviewed path contains named duplicate, cancellation, repeat-unlock, and single-winner controls. It does not represent a full client-side delivery transaction." },
  { label: "Integration contract", title: "Provider-to-access path", state: "REQUIRED", copy: "Provider-event authentication, delivery-ready semantics, and concrete one-time user access remain responsibilities for a defined Adapter and client contract." },
  { label: "External receiver", title: "Signed connectivity", state: "CHECKED", copy: "A signed GitHub `ping` and one authorized redelivery returned HTTP `202`; this verifies a narrow signing path and endpoint reachability, not a live release or Core transition." },
];

export default function PayLock() {
  const [activeStage, setActiveStage] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);

  return (
    <main className="site-shell reference-route-shell paylock-page paylock-reference-page" id="main-content" tabIndex={-1}>
      <a className="skip-link" href="#lifecycle">Skip to main content</a>
      <header className="topbar reference-topbar topbar-scrolled">
        <a className="reference-brand" href="/" aria-label="Return to Deterministic Solutions & Design"><ReferenceMark compact /><span>Deterministic Solutions &amp; Design<small>PayLock / product direction</small></span></a>
        <nav className="desktop-nav reference-nav" aria-label="PayLock navigation"><a href="#lifecycle">Lifecycle</a><a href="#architecture">Architecture</a><a href="#review">Review</a><a href="#evidence">Sources</a><a href="/paylock/catalog">Catalog</a></nav>
        <a className="reference-route-contact" href="mailto:baker@deterministicsolutionsdesign.com">Talk to PayLock <ArrowUpRight size={14} /></a>
        <button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen} aria-controls="paylock-mobile-navigation">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button>
        {menuOpen && <nav className="mobile-menu reference-mobile-menu" id="paylock-mobile-navigation" aria-label="PayLock navigation"><a href="#lifecycle" onClick={() => setMenuOpen(false)}>Lifecycle</a><a href="#architecture" onClick={() => setMenuOpen(false)}>Architecture</a><a href="#review" onClick={() => setMenuOpen(false)}>Review</a><a href="#evidence" onClick={() => setMenuOpen(false)}>Sources</a><a href="/paylock/catalog" onClick={() => setMenuOpen(false)}>Catalog</a><a href="mailto:baker@deterministicsolutionsdesign.com" onClick={() => setMenuOpen(false)}>Talk to PayLock <ArrowUpRight size={14} /></a></nav>}
      </header>

      <section className="product-hero reference-product-hero"><div className="container"><a className="back-link" href="/"><ArrowLeft size={14} /> Deterministic Solutions &amp; Design</a><div className="product-hero-grid"><div><div className="eyebrow reference-product-eyebrow">PayLock / product direction</div><p className="product-commercial-line">Named execution signals. Readable proof path.</p><h1>Make the delivery path<br /><em>clear, bounded, and readable.</em></h1><p>PayLock is a protocol direction for digital-service delivery evidence. It names a request and its agreed signals so the proof path can be read without pretending to own payment, delivery, or a provider’s policy.</p><div className="product-hero-actions"><a className="reference-button reference-button-primary" href="#lifecycle">See the protocol path <ArrowRight size={16} /></a><a className="reference-button reference-button-text" href="/paylock/catalog">Read the catalog <ArrowDownRightIcon /></a></div><div className="product-boundary"><ShieldCheck size={19} /><div><b>Architecture boundary</b><span>Providers keep their own commercial and operating policies. PayLock is designed for delivery evidence, not payment processing or funds control.</span></div></div></div><div className="product-art-frame reference-paylock-art"><div className="paylock-panel-label">Event / reference / proof</div><PayLockMark label="PayLock reference mark" /><div className="art-readout"><span>H0 <i>→</i> ACK + UNLOCK <i>→</i> H1</span><small>Current named proof path</small></div></div></div></div><div className="product-index">PL-01 <span>/</span> Product file</div></section>

      <section className="product-problem section"><div className="container product-two-col"><div className="section-index">01 <span>/</span> The operational gap</div><div><div className="section-kicker">Evidence should match the service</div><h2>An output can exist.<br /><em>Its delivery path should be legible.</em></h2><p className="lead">Digital services often cross providers, applications, devices, and access controls. PayLock supplies a bounded protocol record for the request and the evidence signals that the agreed integration has defined.</p><div className="gap-instrument"><span>STATE OBSERVABILITY</span><div><i /><i /><i /><i className="gap-lost" /></div><b>A delivery path needs a defined, inspectable proof boundary.</b></div><div className="blind-flow"><span>Request</span><ArrowRight size={15} /><span>Execute</span><ArrowRight size={15} /><span>Access</span><ArrowRight size={15} /><span className="muted-node">Assume</span></div><div className="proof-flow"><span>Request</span><ArrowRight size={15} /><span>Bind H0</span><ArrowRight size={15} /><span>Provider ACK</span><ArrowRight size={15} /><span>User Unlock</span><ArrowRight size={15} /><span>Issue H1</span></div></div></div></section>

      <section className="lifecycle section" id="lifecycle"><div className="container"><div className="section-index">02 <span>/</span> Deterministic protocol path</div><div className="section-head-row product-section-head"><div><div className="section-kicker">From request boundary to proof</div><h2>Keep the proof<br /><em>inside the protocol path.</em></h2></div><p>The current reviewed Core path binds H0 and issues H1 only after `provider_ack` and `user_unlock` exist. The event origin and delivery mechanics remain integration-specific responsibilities.</p></div><div className="lifecycle-grid"><div className="lifecycle-rail" role="tablist" aria-label="PayLock lifecycle stages">{stages.map((stage, index) => <button key={stage.number} type="button" role="tab" id={`lifecycle-tab-${stage.number}`} aria-selected={activeStage === index} aria-controls={`lifecycle-panel-${stage.number}`} onClick={() => setActiveStage(index)} className={activeStage === index ? "active" : ""}><span>{stage.number}</span><b>{stage.name}</b><i /></button>)}</div><div className="lifecycle-display" role="tabpanel" id={`lifecycle-panel-${stages[activeStage].number}`} aria-labelledby={`lifecycle-tab-${stages[activeStage].number}`} tabIndex={0}><div className="stage-code"><Check size={13} /> {stages[activeStage].code}</div><span className="stage-number">{stages[activeStage].number}</span><h3>{stages[activeStage].name}</h3><p>{stages[activeStage].copy}</p><div className="stage-art"><span>H0</span><i /><i className={activeStage > 0 ? "lit" : ""} /><i className={activeStage > 1 ? "lit" : ""} /><span className={activeStage === 3 ? "lit" : ""}>H1</span></div></div></div></div></section>

      <section className="governance section"><div className="container"><div className="section-index">03 <span>/</span> Invariants and policy</div><div className="governance-head"><div><div className="section-kicker">Strict proof boundary, adaptable integrations</div><h2>Keep the invariants.<br /><em>Adapt the integration.</em></h2></div><p>The protocol boundary stays stable. Provider and user options—such as compatibility, geography, authentication, retention, or delivery format—belong in the agreed integration contract.</p></div><div className="governance-triad"><article><span>01 / H0</span><CheckCircle2 size={22} /><h3>Bind</h3><p>Core binds the scoped request with a system-issued serial.</p><small>INVARIANT: REQUEST IDENTITY</small></article><article><span>02 / ACK + UNLOCK</span><Layers3 size={22} /><h3>Declare</h3><p>The integration defines and authenticates its readiness event; the user path records its defined unlock signal.</p><small>CONTRACT: INTEGRATION-SPECIFIC</small></article><article><span>03 / H1</span><ShieldCheck size={22} /><h3>Prove</h3><p>Core guards deterministic H1 issuance behind the current named proof signals.</p><small>INVARIANT: GUARDED PROOF</small></article></div></div></section>

      <section className="architecture section" id="architecture"><div className="container"><div className="section-index">04 <span>/</span> Modular architecture</div><div className="center-head"><div className="section-kicker">A clear division of responsibility</div><h2>Integrate without<br /><em>changing the proof boundary.</em></h2><p>PayLock separates the Core protocol, the shared Dictionary meaning, the provider-specific Adapter responsibility, and the provider’s service environment.</p></div><div className="module-grid">{modules.map(module => <article key={module.number}><div className="module-top"><span>MODULE/{module.number}</span>{module.icon}</div><h3>{module.title}</h3><p>{module.copy}</p><small>ROLE → EXPLICIT</small></article>)}</div><div className="resilience-strip"><div><span className="section-kicker">Integration discipline</span><h3>Define the event, authenticate its origin, preserve the evidence boundary.</h3></div><div className="resilience-points"><span><b>Named semantics</b>Dictionary terms prevent event ambiguity.</span><span><b>Authentic source</b>Adapter responsibility before a canonical signal.</span><span><b>Traceable result</b>Core retains the guarded proof transition.</span></div></div></div></section>

      <section className="paylock-review section" id="review"><div className="container"><div className="section-index">05 <span>/</span> Reviewed implementation status</div><div className="paylock-review-head"><div><div className="section-kicker">Evidence-bounded reading guide</div><h2>Show the reviewed path.<br /><em>Keep the open work visible.</em></h2></div><p>PayLock’s public record separates the current reviewed Core behavior from the integration contract still required for any provider-specific deployment. This is how the protocol remains clear without turning a bounded test into a broad claim.</p></div><div className="paylock-review-grid">{implementationStatus.map((item) => <article key={item.title}><div className="paylock-review-top"><span>{item.label}</span><b>{item.state}</b></div><h3>{item.title}</h3><p>{item.copy}</p></article>)}</div><div className="paylock-review-boundary"><ShieldCheck size={19} /><p>These are source-review and bounded-test summaries, not a release certificate. The local Adapter exercise and signed receiver check do not establish a live provider-ready mapping, external one-time user delivery, payment/funds handling, or financial evidence.</p></div><div className="paylock-review-links"><a href="/technical-library#paylock-adapter-local-experiment">Read the local Adapter test record <ArrowUpRight size={15} /></a><a href="/technical-library#paylock-github-signed-connectivity">Read the signed connectivity record <ArrowUpRight size={15} /></a></div></div></section>

      <section className="market section"><div className="container product-two-col"><div className="section-index">06 <span>/</span> Where it applies</div><div><div className="section-kicker">Digital services with a defined proof path</div><h2>When delivery matters,<br /><em>make the evidence scope clear.</em></h2><div className="market-grid"><article><small>WORKFLOW / 01</small><b>Digital APIs</b><p>Define a request and provider-ready outcome around a digital service result.</p></article><article><small>WORKFLOW / 02</small><b>Enterprise SaaS</b><p>Connect a provider-specific readiness event to an explicit delivery evidence path.</p></article><article><small>WORKFLOW / 03</small><b>Programmatic assets</b><p>Establish an inspectable request-to-access record through a defined integration contract.</p></article><article><small>WORKFLOW / 04</small><b>Controlled access</b><p>Design a user-unlock path whose scope and evidence are clear to the affected parties.</p></article></div></div></div></section>

      <section className="product-evidence section" id="evidence"><div className="container"><div className="section-index">07 <span>/</span> Evidence surface</div><div className="evidence-head"><div><div className="section-kicker">Evidence over assumptions</div><h2>Inspect the<br /><em>working surface.</em></h2><p>Review Core source, current evidence records, diagnostics, and the optional reference environment. Each surface has its own stated boundary.</p></div><div className="evidence-art"><div className="evidence-diagram" style={{ padding: "28px", border: "1px solid rgba(184,245,106,0.3)", background: "rgba(18,24,20,0.85)", borderRadius: "4px" }}><div style={{ color: "#7f887d", fontSize: "10px", letterSpacing: "0.14em", textTransform: "uppercase", marginBottom: "14px", fontFamily: "monospace" }}>DETERMINISTIC EVIDENCE SEQUENCE</div><div style={{ display: "flex", flexWrap: "wrap", alignItems: "center", gap: "10px", color: "var(--lime)", fontFamily: "monospace", fontSize: "12px" }}><span style={{ border: "1px solid rgba(184,245,106,0.4)", padding: "4px 10px", background: "rgba(184,245,106,0.06)" }}>H0: BIND</span><span>→</span><span style={{ border: "1px solid rgba(184,245,106,0.4)", padding: "4px 10px", background: "rgba(184,245,106,0.06)" }}>PROVIDER_ACK</span><span>→</span><span style={{ border: "1px solid rgba(184,245,106,0.4)", padding: "4px 10px", background: "rgba(184,245,106,0.06)" }}>USER_UNLOCK</span><span>→</span><span style={{ border: "1px solid #b8f56a", padding: "4px 10px", background: "rgba(184,245,106,0.2)", fontWeight: "bold" }}>H1: PROOF_ISSUED</span></div><p style={{ margin: "16px 0 0", color: "#9da69c", fontSize: "12px", lineHeight: "1.5" }}>Cryptographically bound request identity guarded behind verified provider acknowledgement and user unlock signals.</p></div></div></div><div className="paylock-evidence-list">{evidenceLinks.map((item, index) => <a href={item.href} target="_blank" rel="noreferrer" key={item.title}><span>0{index + 1}</span><div><b>{item.title}</b><small>{item.label}</small></div><ExternalLink size={16} /></a>)}</div></div></section>

      <section className="product-contact section"><div className="container"><div className="contact-callout"><div><div className="section-kicker">Integration & partnership inquiries</div><h2>Build a clear proof path<br /><em>for the service you deliver.</em></h2></div><div className="contact-proof"><ReferenceMark compact /><p>For integration design, protocol boundaries, or product evaluation, contact the PayLock team directly.</p><a className="button button-primary" href="mailto:baker@deterministicsolutionsdesign.com">baker@deterministicsolutionsdesign.com <ArrowUpRight size={16} /></a></div></div></div></section>
      <footer className="reference-footer container"><div className="reference-footer-brand"><ReferenceMark compact /><span>PayLock by Deterministic Solutions &amp; Design LLC</span></div><a href="/">Return to DS&amp;D <ArrowUpRight size={12} /></a><div>Detail / Reference / Action · © 2026 DS&amp;D</div></footer>
    </main>
  );
}

function ArrowDownRightIcon() { return <ArrowRight size={16} className="down-right" />; }
